image: node:10

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
    key: "${CI_PROJECT_ID}_${CI_COMMIT_SHA}"
    untracked: false
    paths:
        - "node_modules/"
        - ".npm/"
        - "cache/Cypress"
             
stages:
  # - build
  - deploy

before_script:
  - npm install --progress=false --no-shrinkwrap

### Build

# build:
#   stage: build
#   script:
#     - npm run docs:build
#   artifacts:
#     expire_in: 1 week
#     paths:
#       - dist

### Deploy
.deploy:
  stage: deploy
  image: python:3.6.8
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - 'pip install -r scripts/deploy/requirements.txt'
  script:
    - cd scripts/deploy && fab ${ENV} deploy

deploy_to_test:
  extends: .deploy
  variables:
    ENV: "test"
    BRANCH: "develop"
  only:
    - develop

# deploy_to_prod:
#   extends: .deploy
#   variables:
#     ENV: "prod"
#   only:
#     - master
