image: node:10

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
    key: "${CI_PROJECT_ID}_${CI_COMMIT_SHA}"
    untracked: false
    paths:
        - "node_modules/"
        - ".npm/"
        - "cache/Cypress"
             
stages:
  - build
  - deploy

before_script:
  - npm install --progress=false --no-shrinkwrap

### Build

build:
  stage: build
  script:
    - npm run docs:build
  artifacts:
    expire_in: 1 hour
    paths:
      - docs/.vuepress/dist

### Deploy
.deploy:
  stage: deploy
  image: python:3.6.8
  before_script:
    - 'pip install -r scripts/deploy/requirements.txt'
  script:
    - cd docs/.vuepress/dist && ls -la
#    - cd scripts/deploy && fab ${ENV} deploy

deploy_to_test:
  extends: .deploy
  variables:
    ENV: "test"
    BRANCH: "develop"
  only:
    - develop

# deploy_to_prod:
#   extends: .deploy
#   variables:
#     ENV: "prod"
#   only:
#     - master
